name: Build

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
    paths:
      - "install/**"
      - "resource/**"
      - "deps/**"
      - ".github/**"

  pull_request:
    branches:
      - "**"
    paths:
      - "install/**"
      - "resource/**"
      - "deps/**"
      - ".github/**"

jobs:
  meta:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
              fetch-depth: 0
        - id: set
          run: |
              is_release=${{ startsWith(github.ref, 'refs/tags/v') }}
              is_pre_release=${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') || contains(github.ref, '-canary') || contains(github.ref, '-rc') }}
              commit_hash=$(git rev-parse --short HEAD)

              if $is_release; then
                tag=$(git describe --tags || true)
              else
                tag=$(git describe --tags --match "v*" --exclude "*-post*" || true)
              fi
              if [[ $tag != v* ]]; then
                if $is_release; then echo "::error::Failed to get tag on releasing" && exit 1; fi
                ver_core=$(curl -sX GET "https://api.github.com/repos/MaaXYZ/MaaFramework/releases/latest" --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | awk '/tag_name/{print $4}' FS='["]' || true)
                tag=$(date "+$ver_core-1%m%d-${commit_hash}")
                if [[ $tag != v* ]]; then
                  tag=$(date "+v%Y.%-m.%-d-2%H%M-${commit_hash}")
                fi
              fi

              if $is_release; then
                version=${tag#v}
              else
                ver_core=${tag%-*-*}
                suffixs=(${tag//-/ })
                tag=${ver_core}-post.${suffixs[-2]}-ci.${{ github.run_id }}
                version=${tag#v}+${commit_hash}.$(date +%Y%m%d)
              fi

              echo "tag=$tag
              version=$version
              is_release=$is_release
              is_pre_release=$is_pre_release" | tee -a "$GITHUB_OUTPUT"
    outputs:
        is_release: ${{ steps.set.outputs.is_release }}
        is_pre_release: ${{ steps.set.outputs.is_pre_release }}
        tag: ${{ steps.set.outputs.tag }} # v<release version> | v<ci version>
        version: ${{ steps.set.outputs.version }} # <release version> | <ci version>+<build> e.g

  Windows:
    needs: meta
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [aarch64,x86_64]
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download MaaFramework
      uses: robinraju/release-downloader@v1.11
      with:
        repository: MaaXYZ/MaaFramework
        fileName: "MAA-win-${{ matrix.arch }}*"
        tag: "v2.1.0-beta.1"
        out-file-path: "deps"
        extract: true

    - name: Move deps to install
      run: |
        move .\deps\bin\* .\install\res
        move .\deps\share\MaaAgentBinary .\install\res
        cp .\README.md .\install
        cp .\LICENSE .\install

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd .\install
        pip install -r requirements.txt

    - name: Copy DLL files to Python directory
      run: |
        cp .\DLLs\msvcp140.dll C:\hostedtoolcache\windows\Python\3.12.4\x64
        cp .\DLLs\vcruntime140.dll C:\hostedtoolcache\windows\Python\3.12.4\x64
        cp .\DLLs\vcruntime140_1.dll C:\hostedtoolcache\windows\Python\3.12.4\x64

    - name: Build executable
      run: |
        cd .\install\
        python build.py
        move .\dist\IdentityV_Tool.exe .\

    - name: Get current commit ID
      run: |
        echo $env:GITHUB_SHA > version
      shell: pwsh

    - name: Upload Assets
      uses: actions/upload-artifact@v4
      with:
        name: IdentityV_Tool-windows-${{ matrix.arch }}-${{ needs.meta.outputs.tag }}
        path: |
          .\install
          !.\install\deps
          !.\install\build
          !.\install\*.spec
          !.\install\*.py
          !.\install\requirements.txt

  Macos:
      needs: meta
      strategy:
        matrix:
            include:
                - os: macos-13
                  arch: x86_64
                - os: macos-14
                  arch: aarch64
        fail-fast: false
      runs-on: ${{ matrix.os }}

      
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download MaaFramework
        uses: robinraju/release-downloader@v1.11
        with:
          repository: MaaXYZ/MaaFramework
          fileName: "MAA-macos-${{ matrix.arch }}*"
          tag: "v2.1.0-beta.1"
          out-file-path: "deps"
          extract: true

      - name: Move deps to install
        run: |
          mv ./deps/bin/* ./install/res
          mv ./deps/share/MaaAgentBinary ./install/res
          cp ./README.md ./install
          cp ./LICENSE ./install

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd ./install
          pip install -r requirements.txt

      - name: Build executable
        run: |
          cd ./install
          python build.py
          ls -la
          mv ./dist/IdentityV_Tool.exe ./

      - name: Get current commit ID
        run: |
          echo $env:GITHUB_SHA > version
        shell: pwsh
    
      - name: Upload Assets
        uses: actions/upload-artifact@v4
        with:
          name: IdentityV_Tool-macos-${{ matrix.arch }}-${{ needs.meta.outputs.tag }}
          path: |
            ./install
            !./install/deps
            !./install/build
            !./install/*.spec
            !./install/*.py
            !./install/requirements.txt


  release:
    if: ${{ needs.meta.outputs.is_release == 'true' }}
    needs: [meta, windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: assets
          

      - run: |
          cd assets
          for f in *; do
            (cd $f && zip -r ../$f.zip .)
          done
      - uses: softprops/action-gh-release@v2
        with:
          files: assets/*
          tag_name: ${{ needs.meta.outputs.tag }}
          prerelease: ${{ needs.meta.outputs.is_pre_release == 'true' }}